/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppGradesRouteImport } from './routes/_app.grades'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCoursesRouteImport } from './routes/_app.courses'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app.students.$studentId'
import { Route as AppCoursesCourseIdRouteImport } from './routes/_app.courses.$courseId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AppAdminRoute
  '/applications': typeof AppApplicationsRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/grades': typeof AppGradesRoute
  '/profile': typeof AppProfileRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AppAdminRoute
  '/applications': typeof AppApplicationsRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/grades': typeof AppGradesRoute
  '/profile': typeof AppProfileRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/courses': typeof AppCoursesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/grades': typeof AppGradesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin'
    | '/applications'
    | '/courses'
    | '/dashboard'
    | '/grades'
    | '/profile'
    | '/students'
    | '/courses/$courseId'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin'
    | '/applications'
    | '/courses'
    | '/dashboard'
    | '/grades'
    | '/profile'
    | '/students'
    | '/courses/$courseId'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/_app/admin'
    | '/_app/applications'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/grades'
    | '/_app/profile'
    | '/_app/students'
    | '/_app/courses/$courseId'
    | '/_app/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grades': {
      id: '/_app/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/courses/$courseId': {
      id: '/_app/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppCoursesRoute
    }
  }
}

interface AppCoursesRouteChildren {
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesCourseIdRoute: AppCoursesCourseIdRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppStudentsRouteChildren {
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppGradesRoute: typeof AppGradesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppGradesRoute: AppGradesRoute,
  AppProfileRoute: AppProfileRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
