input {
  http {
    port => 5044
    codec => json
    ecs_compatibility => v8
  }
}

filter {
  if [request_id] {
    mutate {
      copy => { "request_id" => "correlation_id" }
    }
  }
}

output {
  elasticsearch {
    hosts => [ "http://elasticsearch:9200" ]
    index => "fastapi-logs-%{+YYYY.MM.dd}"
    data_stream => false
  }
}
